Add Dashboard Schematic
olin-electric-motorsports/olin-electric-motorsports pull request #181
Opened 2022-11-07 02:38 UTC by amandalchang

Created entire schematic, which includes three LSDs in hierarchical sheets, a 5V buck converter, and my estop shutdown sense.

2022-11-15 15:44 UTC, jack-greenberg commented on vehicle/mkvi/hardware/nostril/dashboard/BUILD
> +    name = "template_board",
Can you update the BUILD file to match your project (ask Amit for examples) so that this passes CI properly :)

2022-11-15 15:53 UTC, jack-greenberg requested changes
Awesome job! This schematic looks super clean and is really easy to read. Couple things:

![image](https://user-images.githubusercontent.com/7565220/201964171-5d79a58a-0863-4ab5-ad45-a198c56ccc9f.png)
* We need to do this now :/ I can help or you can talk to Amit or Dasha or Elvis
* Your CAN+ and CAN- aren't connected to anything. 
* Make sure to run ERC (electrical rule checker) and try and resolve as many issues as you can. Ask your subteam lead for help if you are unclear about this.

Other than that, looks great! Awesome job :)

2022-12-05 13:08 UTC, jack-greenberg commented
Is this supposed to have a buck converter on it? I thought we discussed removing it?

2022-12-24 16:56 UTC, jack-greenberg commented
This layout looks great! Love the package shape. Couple notes:

# Schematic
* You should have a pull-down resistor on `RTD_BUTTON_SENSE-` so that it isn't floating when the button is not pressed
* R15 should be R_120_DNP
* In the MCP25625 schematic sheet, MISO should be an output hierarchical label, its currently an input (make sure to update the pins on the top-level schematic too)
* Do we know how much current the buzzer and dashboard LEDs draw? If it's anywhere near 500mA, we should use multiple pins on the M.2 for the low-side connections. Might also want to make the traces a bit wider, maybe 10mils instead of 6.
* The *_SHDN_SENSE pins should be outputs (make sure to update the pins on the top-level schematic too)
![image](https://user-images.githubusercontent.com/7565220/209444596-8d129b53-6b37-4dea-9c3b-8367fcbb2218.png)

# Layout
* Most of this looks really good.
* In general, you've got a lot of room on this board, so I'd recommend spacing things out a little more so that 
* Image below, you should give each pad on the crystal its own GND via for signal integrity. Also, the load capacitors and 3V3 bypass capacitor should also have their own GND vias too
![image](https://user-images.githubusercontent.com/7565220/209444354-32630bcf-0b01-4bba-b6a6-1a2849093f81.png)
* Same here (below). In general, use one via per ground pad
![image](https://user-images.githubusercontent.com/7565220/209444574-e3cdacf4-1919-47b2-b588-9866c5148e7e.png)

2022-12-24 16:56 UTC, jack-greenberg requested changes
See prev comment

2022-12-24 18:13 UTC, amit-kumarh commented
Buzzer and panel lights are both <80 mA so should be fine on that front

2022-12-27 14:05 UTC, jack-greenberg commented
Leaving this here for posterity's sake: @amit-kumarh and I chatted on Slack yesterday after realizing that the current footprint and placement for the Pi Zero means that it will be sticking off of the dashboard PCB instead of hovering right over it.

It will work, and we're definitely not pressed for space, so we can leave it be, but we can also re-place and re-route the board so that it's a bit cleaner. Either way, Amit will switch gears to focus on the motherboard and I might reroute it if I get the time, otherwise we can just merge. If anyone else has thoughts put them here!

2023-01-04 17:16 UTC, amit-kumarh commented
Oh! One more thing - trace angle got a little wonky here, mind just making those 45 degree angles?

![trace_angle](https://user-images.githubusercontent.com/51718056/210612111-2752da3c-9889-464d-839f-8cad748bcb35.png)

2023-01-04 20:19 UTC, jack-greenberg commented
* For the crystal, I kept the distance I did because I didn't want the CAN signals to interfere with them. From other crystal designs I've seen, this shouldn't cause any issues
* Ah yeah, for the vias, I found that smaller vias worked better for the design, but I'll double check the Coda page
* W/r/t the ground test pad, yeah I struggled a bit with that. The issue is that having all of the test points close together made routing super difficult, so I decided to prioritize routing

2023-01-05 09:38 UTC, jack-greenberg commented
w/r/t the via sizing and trace clearance, I think it should all be within the capabilities of Calpak, although they don't publicly list their capabilities (nowhere that I can find lol). I'll update the minimums on KiCad to get rid of the warnings if that's okay?

2023-01-05 23:19 UTC, elviswolcott approved these changes

2023-01-05 23:20 UTC, merged