Added Schematic for TSAL and AIL
olin-electric-motorsports/olin-electric-motorsports pull request #184
Opened 2022-11-08 03:21 UTC by VintageBikes

first draft, change connector to M.2, changed hv output to 5v, removed hv linreg

2022-12-23 17:33 UTC, bubbleebubbles submitted a review, later dismissed
Great job so far! Please see some feedback below: 
## TSAL/AIL Layout Feedback
* This board will be stepping down from 400V to 5V, which is a lot. We want to make sure that we're dissipating a lot of the heat and that we're getting good performance out of this circuit. On the [buck converter datasheet page 16](https://www.monolithicpower.com/en/documentview/productdocument/index/version/2/document_type/Datasheet/lang/en/sku/MP9488/document_id/3748/) they have some layout guidelines that I strongly recommend to follow. Try your best to arrange the components and add the copper pours they suggest so that we can get good porformance out of this power regulator. 
![1](https://user-images.githubusercontent.com/64562621/209375427-b87c8078-eac7-4c1a-ad1f-3cbbca07910d.png)

* HV and LV need to be separated at lest 12.7mm according to the rules and clearly marked. Make sure to add a silkscreen with the distance between the two. I don't think it's separated enough at the moment (your copper pours on the back are 10-ish mm apart). 
![2](https://user-images.githubusercontent.com/64562621/209375830-e4fd03a2-6363-41b2-8169-c7c70dba5860.png)
![3](https://user-images.githubusercontent.com/64562621/209375964-9c4e61e2-961c-45c4-9ab4-40dc26a2c13e.png)

* Bypass capacitors need to be placed as close as possible to the power supply pin of the part they're meant for and connected without any interuptions. 
![4](https://user-images.githubusercontent.com/64562621/209376160-5ebc11d4-9fd0-4b74-b6d9-a623fdc88c75.png)

* Make sure to label all your test points clearly with the signal. You did that for some of them but not all. 

* These resistors (R1, 4, 7, 8) have gotten so hot that they've melted off in the past. These need to be spread out and need to add a copper pour underneath to help with heat dissipation. 
![5](https://user-images.githubusercontent.com/64562621/209377412-407051b6-006b-420a-9db1-7e89ad88e354.png)

Great first pass! Feel free to shoot me a slack message if any of this is confusing. Thanks for the hard work!

2023-01-02 22:15 UTC, jack-greenberg requested changes
Looks like there are some DRC errors to do with the board outline :/

2023-01-03 16:16 UTC, bubbleebubbles commented
> Looks like there are some DRC errors to do with the board outline :/

yee, working on that lol :D

2023-01-06 07:43 UTC, elviswolcott approved these changes

2023-01-06 07:45 UTC, merged